{
    "name": "Salesperson Live Tracking",
    "summary": "Full salesperson field tracking: GPS, check-in/out, selfie proof, KPI, alerts, offline sync, CRM integration",
    "version": "19.0.2.0.0",
    "category": "Sales/Sales",
    "author": "Your Name",
    "depends": [
        "sale_management",
        "base_geolocalize",
        "crm",
        "mail",
    ],
    "data": [
        "security/salesperson_tracking_groups.xml",
        "security/salesperson_tracking_security.xml",
        "security/ir.model.access.csv",
        "security/ir.rule.xml",
        "reports/report_visit_plan.xml",
        "reports/report_salesperson_tracker.xml",
        "views/salesperson_tracking_views.xml",
        "views/salesperson_visit_plan_views.xml",
        "views/salesperson_checkin_views.xml",
        "views/salesperson_kpi_views.xml",
        "views/res_users_views.xml",
        "views/templates.xml",
        "views/dashboard_template.xml",
        "views/salesperson_location_backup_views.xml",
        "views/menus.xml",
        "data/mail_template_data.xml",
        "data/location_data_policy_cron.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "salesperson_live_tracking/static/src/css/style.css",
        ],
    },
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}