from . import res_users
from . import salesperson_visit_plan_line
from . import salesperson_visit_plan
from . import salesperson_tracker
from . import salesperson_location_log
from . import salesperson_checkin
from . import salesperson_tracking_session
from . import salesperson_location_backup
from . import res_config_settings
